export type PresetWallpaperId = "blossom" | "fuji" | "anime-sky" | "tokyo-neon" | "blueprint" | "studio" | "mist";
export type WallpaperId = PresetWallpaperId | "custom";
export type WallpaperMotionMode = "still" | "breathe" | "cinematic" | "follow";
export type WallpaperFile = { url: string; name: string; kind: "image" | "video"; sourcePath?: string };
export type RecentWallpaper = { path: string; name: string; kind: "image" | "video" };

export type ProjectRecord = {
  id: string;
  name: string;
  sourcePath?: string;
  createdAt: string;
  updatedAt: string;
  archivedAt?: string;
};

export type ApiIntegrationMode = "codex_cli" | "cc_switch";
export type AgentProviderId = "codex" | "claude" | "gemini" | "opencode";
export type ApiProviderSummary = {
  id?: string;
  name?: string;
  active?: boolean;
  endpoint?: string;
  model?: string;
  hasApiKey?: boolean;
  redactedApiKey?: string;
  appType?: AgentProviderId;
  models?: string[];
  credentialStatus?: "oauth" | "managed" | "route";
  authLabel?: string;
};
export type CcSwitchSync = {
  source?: string;
  rootPath?: string;
  configPath?: string;
  databasePath?: string;
  settingsPath?: string;
  syncedAt?: string;
  codexCurrent?: string;
  claudeCurrent?: string;
  codexProviders?: ApiProviderSummary[];
  claudeProviders?: ApiProviderSummary[];
  geminiProviders?: ApiProviderSummary[];
  opencodeProviders?: ApiProviderSummary[];
  providersByAgent?: Partial<Record<AgentProviderId, ApiProviderSummary[]>>;
  settings?: {
    currentProviderCodex?: string;
    currentProviderClaude?: string;
    enableLocalProxy?: boolean;
    enableFailoverToggle?: boolean;
    skillSyncMethod?: string;
  };
};
export type ApiIntegrationConfig = {
  mode: ApiIntegrationMode;
  agentProvider: AgentProviderId;
  providerName: string;
  endpoint: string;
  model: string;
  keyStatus: "missing" | "configured" | "synced";
  lastSyncAt?: string;
  sourcePath?: string;
};
export type KnowledgeBaseConfig = {
  cloudEnabled: boolean;
  localRoots: string[];
  endpoint: string;
  namespace: string;
  tokenEnv: string;
  topK: number;
};
export type AppSettings = {
  activeWallpaper: WallpaperId;
  customWallpaperPath?: string;
  wallpaperBrightness: number;
  wallpaperBlur: number;
  wallpaperVignette: number;
  workspaceOpacity: number;
  wallpaperMotionMode: WallpaperMotionMode;
  wallpaperMotionStrength: number;
  defaultWallpaperVersion?: number;
  panelOpacityVersion?: number;
  recentWallpapers: RecentWallpaper[];
  projects?: ProjectRecord[];
  activeProjectId?: string;
  projectName?: string;
  recentProjectPath?: string;
  apiConfig?: ApiIntegrationConfig;
  knowledgeBase?: KnowledgeBaseConfig;
};

export type CodexConfig = {
  objective: string;
  cadApplication: "auto" | "solidworks" | "autocad" | "both";
  target: "auto" | "general_part" | "assembly" | "shell" | "fixture" | "sheet_metal" | "holes" | "drawing" | "package" | "reverse" | "skill";
  expectedOutput: "auto" | "cad_files" | "drawing_package" | "research_report";
  process: "auto" | "FDM" | "SLA" | "CNC" | "sheet_metal";
  material: "auto" | "PLA" | "PETG" | "ABS" | "Al6061";
  unit: "mm";
  length: number;
  width: number;
  height: number;
  wallThickness: number;
  outputDir: string;
  strictGbDrawing: boolean;
  realCutouts: boolean;
  localCadAutomation: boolean;
};
export type AutomationJobKind = "create_shell" | "import_model" | "delivery_package" | "dfm_review" | "codex_task" | "agent_task";
export type AutomationJobStatus = "queued" | "running" | "passed" | "review_required" | "failed" | "cancelled" | "approval_required" | "blocked";
export type WorkerLogEntry = { status?: string; message?: string; at?: string; worker?: string; runnerId?: string; data?: unknown };
export type ArtifactRecord = {
  kind?: string;
  path?: string;
  type?: "artifact" | "preview" | string;
  format?: string;
  sourceArtifact?: string;
  sourceBackend?: string;
  previewManifest?: string;
  fallback?: string;
  isDemo?: boolean;
  interactive?: boolean;
  exists?: boolean;
  isDirectory?: boolean;
  sizeBytes?: number;
  sha256?: string;
  producedThisRun?: boolean;
};
export type ReviewCheck = { id?: string; severity?: string; status?: "pass" | "warning" | "fail" | string; message?: string };
export type DomainEvidence = {
  status?: string;
  stage?: string;
  manual_review_required?: boolean;
  retryable?: boolean;
  error_code?: string | null;
  limitations?: string[];
  [key: string]: unknown;
};
export type ArtifactRelation = { from?: string; to?: string; type?: string; relation?: string; [key: string]: unknown };
export type BackendDiagnostic = {
  backend?: string;
  status?: "pass" | "pilot" | "blocked" | "failed" | string;
  stage?: string;
  error_code?: string | null;
  retryable?: boolean;
  limitations?: string[];
};
export type JobRunSnapshot = {
  runId?: string;
  status?: AutomationJobStatus;
  stage?: string;
  createdAt?: string;
  updatedAt?: string;
  lastMessage?: string;
  error?: string;
  result?: AutomationJob["result"];
  artifacts?: ArtifactRecord[];
  artifactLedgerPath?: string;
  reviewGatePath?: string;
  reviewGate?: AutomationJob["reviewGate"];
  drawingEvidence?: DomainEvidence;
  bomEvidence?: DomainEvidence;
  dfmEvidence?: DomainEvidence;
  reviewFindings?: Array<Record<string, unknown>>;
  artifactRelations?: ArtifactRelation[];
  blockedReasons?: string[];
};
export type RetryPolicy = {
  previousRunId?: string;
  retryFromStage?: string;
  scope?: "failed_stage_and_downstream" | string;
  preservePreviousArtifacts?: boolean;
  overwrite?: boolean;
  requestedAt?: string;
};
export type AutomationJob = {
  schemaVersion: "1.0" | "2.0";
  id: string;
  runId: string;
  kind: AutomationJobKind;
  title: string;
  detail: string;
  status: AutomationJobStatus;
  progress: number;
  createdAt: string;
  updatedAt: string;
  requestedBy: string;
  createdByAppVersion: string;
  projectId?: string;
  conversationId?: string;
  inputs?: Array<Record<string, unknown>>;
  stage?: "intake" | "planning" | "checking" | "launching" | "executing" | "reviewing" | "delivery" | "blocked";
  capabilitySnapshot?: Record<string, unknown>;
  assumptions?: Array<Record<string, unknown>>;
  requiredArtifacts?: string[];
  preferredBackend?: "auto" | "headless" | "solidworks" | "autocad";
  requiredOutputs?: string[];
  nativeFormatRequired?: boolean;
  fallbackPolicy?: "allow_open_formats" | "native_only" | "blocked";
  previewManifest?: string;
  evidenceGraph?: Record<string, unknown>;
  verificationEvidence?: Array<Record<string, unknown>>;
  drawingEvidence?: DomainEvidence;
  bomEvidence?: DomainEvidence;
  dfmEvidence?: DomainEvidence;
  reviewFindings?: Array<Record<string, unknown>>;
  artifactRelations?: ArtifactRelation[];
  backendDiagnostics?: Record<string, BackendDiagnostic> | BackendDiagnostic[];
  runHistory?: JobRunSnapshot[];
  retryPolicy?: RetryPolicy;
  blockedReasons?: string[];
  projectPath?: string;
  executor?: "mock" | "codex" | "agent";
  objective?: string;
  targetSoftware?: string;
  target?: string;
  expectedOutput?: string;
  strictRules?: string[];
  capabilities?: string[];
  prompt?: string;
  cwd?: string;
  skillPath?: string;
  lastMessage?: string;
  workerLog?: Array<WorkerLogEntry | string>;
  leaseUntil?: string;
  heartbeatAt?: string;
  runnerId?: string;
  workerPid?: number;
  result?: {
    mode?: string;
    outputPath?: string;
    message?: string;
    outputs?: Record<string, string> | Array<string | ArtifactRecord>;
    artifacts?: Array<string | ArtifactRecord>;
    verification?: Array<Record<string, unknown>>;
    features?: Array<Record<string, unknown>>;
    checks?: ReviewCheck[];
    stdoutTail?: string;
    stderrTail?: string;
    engineeringPlanPath?: string;
    engineeringPlan?: { phases?: Array<{ id?: string; name?: string; status?: string; human_gate?: boolean }> };
    backendDiagnostics?: Record<string, BackendDiagnostic> | BackendDiagnostic[];
  };
  uiConfig?: Record<string, unknown>;
  policy?: {
    sandbox: "read-only" | "workspace-write" | "danger-full-access";
    approval: "never" | "manual-required";
    requireSkillRead: boolean;
    requireTests: boolean;
    requireCommit: boolean;
    requirePush: boolean;
    requireReviewerPass: boolean;
  };
  artifacts?: ArtifactRecord[];
  approvalReasons?: string[];
  approvedAt?: string;
  approvedBy?: string;
  approvedPolicyReasons?: string[];
  reviewedAt?: string;
  reviewedBy?: string;
  reviewDecision?: "approved" | "rejected";
  reviewNote?: string;
  artifactLedgerPath?: string;
  reviewGatePath?: string;
  reviewGate?: {
    status?: "pass" | "warning" | "fail";
    checks?: ReviewCheck[];
    manualReview?: { status?: "approved" | "rejected"; reviewedBy?: string; reviewedAt?: string; note?: string };
  };
  error?: string;
};
export type QueueEvent = { type?: string; jobId?: string; status?: string; message?: string; at?: string; progress?: number; worker?: string; runId?: string; runnerId?: string; data?: unknown };
export type QueueLogTail = { stdoutPath?: string; stderrPath?: string; stdout?: string; stderr?: string };
export type AgentChatMessage = { id: string; role: "user" | "assistant" | "system"; content: string; at: string; jobId?: string; projectId?: string; conversationId?: string };
export type AgentConversation = { id: string; projectId: string; title: string; provider: AgentProviderId; model: string; createdAt: string; updatedAt: string };
export type ManualReviewDraft = { note: string; checks: string[] };
export type HelpTopicId = "start" | "projects" | "status" | "delivery" | "troubleshooting";
export type SubmissionKind = "task" | "chat" | null;
export type WorkerStatus = { running: boolean; pid?: number | null; recoveredJobs?: number; message: string; health?: { status?: string; heartbeatAt?: string; queue?: Record<string, number> } | null };
export type RuntimeRemediation = {
  id: string;
  title: string;
  reason?: string;
  required?: boolean;
  installCommand?: string;
  downloadUrl?: string;
};
export type RuntimeHealth = {
  skillRoot: string;
  solidworksSkillPath: string;
  autocadSkillPath: string;
  defaultOutputDir?: string;
  python?: { ok?: boolean; entry?: string; message?: string };
  codex?: { version?: { ok?: boolean; message?: string }; login?: { ok?: boolean; message?: string }; entry?: string };
  agentProviders?: Array<{ id: AgentProviderId; name: string; installed?: boolean; ready?: boolean; verified?: boolean; status?: "not_installed" | "auth_failed" | "verified" | "verification_required"; version?: { ok?: boolean; message?: string }; auth?: { ok?: boolean | null; message?: string }; entry?: string }>;
  doctor?: { schemaVersion?: string; summary?: { status?: "passed" | "warning" | "error"; errors?: number; warnings?: number }; checks?: Array<Record<string, unknown>>; error?: string };
  remediations?: RuntimeRemediation[];
  solidworks?: { ok?: boolean; message?: string };
  autocad?: { ok?: boolean; path?: string };
  capabilityManifest?: { schema_version?: string; verified_versions?: Record<string, string[]>; capabilities?: Array<Record<string, unknown> & { id?: string; level?: string }> };
};
export type ImportedWallpaper = { path: string; name: string; kind: "image" | "video" };
export type AppStoreMigrationStatus = {
  storage: "sqlite";
  schemaVersion: number;
  source: Record<string, number>;
  indexed: Record<string, number>;
  countsMatch: boolean;
};
